{\rtf1\ansi\ansicpg1252\cocoartf2820
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 // Code your testbench here\
// or browse Examples\
module tb_full_adder;\
  \
  reg [3:0] a,b;\
  reg cin;\
  wire cout;\
  wire [3:0] sum;\
  \
  full_adder uut(\
    .a(a),\
    .b(b),\
    .cin(cin),\
    .sum(sum),\
    .cout(cout)\
    \
  );\
  \
  initial begin\
    \
    $monitor("Time=%0t | a=%b, b=%b, cin=%b -> sum=%b, cout=%b", $time, a, b, cin, sum, cout);\
    \
    a = 4'b0001; b=4'b0010; cin = 1'b0; #10;\
    a = 4'b1101; b=4'b0101; cin = 1'b1; #10;\
    a = 4'b1111; b=4'b1111; cin = 1'b0; #10;\
    a = 4'b1001; b=4'b0110; cin = 1'b1; #10;\
    a = 4'b0000; b=4'b0000; cin = 1'b1; #10;\
    a = 4'b1010; b=4'b0101; cin = 1'b0; #10;\
    \
    $finish;\
    \
  end\
endmodule}